version: '42'
services:
    ebot-web:
        build:
            context: ./ebot-web
        environment:
            - EBOT_ADMIN_LOGIN
            - EBOT_ADMIN_PASSWORD
            - EBOT_ADMIN_EMAIL
        volumes:
            - "eBotWebVolume:/app/eBot-CSGO-Web"
            - "./ebot-logs:/app/ebot-logs"
            - "./ebot-demos:/app/ebot-demos"
            - "./etc/eBotWeb/app_user.yml:/app/eBot-CSGO-Web/config/app_user.yml"
            - "./etc/eBotWeb/databases.yml:/app/eBot-CSGO-Web/config/databases.yml"
        depends_on:
            - mysqldb
    ebot-socket:
        build:
            context: ./ebot-socket
        ports:
            - "12360:12360"
        volumes:
            - "./ebot-logs:/app/eBot-CSGO/logs"
            - "./ebot-demos:/app/eBot-CSGO/demos"
            - "./etc/eBotSocket/config.ini:/app/eBot-CSGO/config/config.ini"
        depends_on:
            - mysqldb
            - ebot-web
            - redis
    ebot-logs-receiver:
        build:
            context: ./ebot-logs-receiver
        ports:
            - "12345:12345"
        volumes:
            - "./etc/eBotLogReceiver/config.json:/app/ebot-project/configs/config.json"
        depends_on:
            - redis
    mysqldb:
        image: biarms/mysql:5.7
        restart: always
        environment:
            - MYSQL_DATABASE
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - ./data/redis:/data
volumes:
    eBotWebVolume:
